name: Android CI

on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 12 * * *'
    - cron: '59 23 * * *'
    - cron: '50 11 * * *'

jobs:

  build-debug:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone BiliClient
      run: cd .. && sudo rm -rf action_build_biliclient && git clone -b develop https://github.com/huanli233/BiliClient.git action_build_biliclient
    - name: ls
      run: ls -l /home/runner/work/action_build_biliclient/action_build_biliclient
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: mkdir
      run: mkdir out
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: |
          ./gradlew :app:assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk out/app-debug.apk
    - name: Upload APK(debug)
      uses: actions/upload-artifact@v4
      with:
          name: app-debug
          path: out/app-debug.*

  build-release:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone BiliClient
      run: cd .. && sudo rm -rf action_build_biliclient && git clone -b develop https://github.com/huanli233/BiliClient.git action_build_biliclient
    - name: ls
      run: ls -l /home/runner/work/action_build_biliclient/action_build_biliclient
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
          ./gradlew :app:assembleRelease
    - uses: ilharp/sign-android-release@nightly # Or use @nightly
      name: Sign app APK
      id: sign_app
      with:
        releaseDir: app/build/outputs/apk/release
        signingKey: ${{ secrets.KEY_STORE }}
        keyAlias: ${{ secrets.ALIAS_NAME }}
        keyStorePassword: ${{ secrets.KEY_PASSWORD }}
        keyPassword: ${{ secrets.ALIAS_PASSWORD }}
        buildToolsVersion: 30.0.3
    - name: Upload APK(release)
      uses: actions/upload-artifact@v4
      with:
          name: app-release
          path: ${{steps.sign_app.outputs.signedFile}}
